### ISSUE TITLE
Windows work

### ISSUE THREAD

**Issue by LuisCastilloV98** [masesgroup/JCOBridge-Examples#1]
I have tried to implement your example (the one you have on youtube) and it does not work, I am working on a windows pc, set the JVMPath to "@" C: \ Program Files \ Java \ jre1.8.0_281 \ bin \ javaw.exe " "  and it does not work. Add image of the error showing, greetings.
![Error1](https://user-images.githubusercontent.com/28116477/112499418-1046b680-8d4d-11eb-81de-0b334cb988b6.PNG)

**Comment by LuisCastilloV98** [comment]
Correct path is:             public override string JVMPath { get { return @"C:\Program Files\Java\jre1.8.0_281\bin\server\jvm.dll"; } }

**Comment by mariomastrodicasa** [comment]
> Correct path is: public override string JVMPath { get { return @"C:\Program Files\Java\jre1.8.0_281\bin\server\jvm.dll"; } }

@LuisCastilloV98 you are right. JCOBridge expect the path to JVM.dll which is the real Java Virtual Machine: **java.exe** or **javaw.exe** are the CLI interfaces to the JVM.
