### ISSUE TITLE
Import external libs

### ISSUE THREAD

**Issue by LuisCastilloV98** [masesgroup/JCOBridge-Examples#2]
Is possible to import external libs in a specific path?

**Comment by mariomastrodicasa** [comment]
Hi @LuisCastilloV98,
this repo was not watched until now and we miss your question. We are moving completely on github in the last weeks.
Does your question was for .NET side or JVM/Java side?

Anyway, from .NET side it is possible to add any JAR in the Classpath like any other Java application.
From JVM/Java application it is possible to use these APIs: [AddPath](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCOBridge.html#AddPath-java.lang.String-) and [AddReference](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCOBridge.html#AddReference-java.lang.String-).

Try to look in [JCOReflector](https://github.com/masesgroup/JCOReflector) or [KafkaBridge](https://github.com/masesgroup/KafkaBridge) to see some real usage.
